### ISSUE TITLE
Guitar Pedal Settings Storage is currently limited to 8 active effects with 16 parameters each

### ISSUE THREAD

**Issue by bkshepherd** [bkshepherd/DaisySeedProjects#13]
The current software implemented of local storage on QSPI for the storage of effect parameters settings is quite simplistic and limited.   

The current implementation in guitar_pedal_storage.h & .cpp is hard coded to treat each effect parameter as a u_int8 type and to simply allocated a block of memory in the QSPI region that is SETTINGS_MAX_EFFECT_COUNT * SETTINGS_MAX_PARAM_COUNT * sizeof(u_int8) bytes. Using this approach, it's quite easy to look up the stored value for a parameter by simply using an offset into this block of memory.  Unfortunately, this is quite limited and not very flexible for future use. In the current code base SETTINGS_MAX_EFFECT_COUNT is set to 8 and SETTINGS_MAX_PARAM_COUNT is set to 16.  Which effectively limits the device to a max of 8 active effects with up to 16 parameters each.  This is not a hardware memory limit.  Those numbers were chosen quite arbitrarily.  If you need more parameters feel free to adjust those defines for your own purposes.

This presents a great opportunity for someone wanting to contribute to the project to get started with something that wouldn't be too hard to improve.  Some ideas that would make this a lot more flexible:

- Allow an arbitrary number of presets
- Allow an arbitrary number of effect parameters per preset
- Only allocate the actual  amount of storage needed to save a preset for a particular effect module
- Support additional stored data types beyond u_int8.  In would be nice to store some parameters as floats for instance.
- Bonus points if presets stored in the old format can easily be updated to the new format.

**Comment by bkshepherd** [comment]
Yes, this is fairly similar to what I was thinking.   I think the main thing I was initially thinking was to just change the persistent storage class to work on 32bit segments of data instead of 8bit.  That way, you could simply type cast the bytes to whatever type the parameter is expecting 32bit int, 32bit float, etc.   But instead of adding a new enumeration for the storage type, I'd just use the ParameterValueType to infer how it should treat the underlying 32bits of data for that parameter (as a int or float or whatever). Pretty similar to what you proposed, but I think your idea lets some of the smaller sizes still take up less data in storage, which is nice.

The other thing that becomes a bit tricky is that each effect would now have a variable size block of data for storage, so in the guitar_pedal_storage classes, you'd have to update the various helper function to know what the offset into the data is for the stored parameters for this effect.  It might be necessary to have a map of start offsets for each effect on the Settings struct.

If this is something you want to work on improving, sounds great!  I'm definitely happy to accept pull requests. 

Thank you!

**Comment by jaching** [comment]
Thanks for the feedback!  You gave me more to consider, as I was fairly stuck on the idea of maintaining legacy behavior.  But I like what you initially had in mind better than my proposal.

I didn't consider the extra tracking that would be required, for some reason I thought it would be easy to add this as a parameter in ParameterMetaData, but this is a constant would require the end user to explicitly map this size (which adds an extra margin of error, for no reason,) or use the method that you suggested, which is use another array to track start offsets, which means allocating more RAM just to know the offset. 

But the more thinking about using the byte method, the software would be incrementing through each element array, which would add a performance cost, compared to creating helper functions that explicitly cast the correct data type on the uint32.

Additionally, I have the feeling that running out of QSPI for storing 32 bits parameters, might be the least of concerns, since we have 8MB of data to work with (so in the ball park of 2 million 32 bit parameters, around 1M if you redundant copies, less if you additionally want to also store CRC , etc.).

I'd be more than happy to take this on, so I will start now.

**Comment by jaching** [comment]
Hello @bkshepherd ,

I forgot to ask this before, but can you add me as a contributor so that I can create a branch for a pull request?

I also wanted to provide an update from my side.  I ended up having to attend a conference this week and unfortunately getting covid as well, and as such.

I was able to add the following (but am still in the process of checking that I did not break anything UI/audio wise from these changes).  If any of this is not intended, please let me know (or after I create the pull request), and I can revert.

**Changes:**
- Arbitrary number of presets per effect (there is just a global limitation provided by the maximum size of globalEffectsSettings array), 
- Note: I have not had the chance to check this, as I haven't added a way to do this in the settings menu yet to swap presets/add more, but I do have functions which will shift the storage words accordingly if a new preset is added for an effect.
- Arbitrary number of effects (determine by the number of parameters in Meta Data)
- Added a check for when the end user has added new parameters to an effect, when this is the case, shift the rest of the persistent memory buffer to ensure that no presets are lost in the process.
- Changed the base storage type to uint32
- Changed IntMappings such that an arbitrary min and max are range is used/displayed
- Changed FloatMagnitude enum to Float, and changed from IntMapping to FloatMapping, and added new methods to get Float values, (e.g. the end user can now change a Wet parameter to min:0%, max:100% with floating point precision in between)

**Example Persistent Storage globalEffectsSettings format (e.g. say we have 2 Effects):**
[0] Current sum of all Effects/Presets/Parameters
[1] Number of Parameters for Effect 0 (e.g. 3)
[2] Number of Presets for Effect 0 (e.g. 2)
[3] Effect 0: Preset 0: Parameter 0 (e.g. 123)
[4] Effect 0: Preset 0: Parameter 1 (e.g. 14)
[5] Effect 0: Preset 0: Parameter 2 (e.g. 54)
[6] Effect 0: Preset 1: Parameter 0 (e.g. 1)
[7] Effect 0: Preset 1: Parameter 1 (e.g. 154)
[8] Effect 0: Preset 1: Parameter 2 (e.g. 84)
[9] Number of Parameters for Effect 1 (e.g. 2)
[10] Number of Presets for Effect 1 (1)
[11] Effect 1: Preset 0: Parameter 0 (e.g. 0)
[12] Effect 1: Preset 0: Parameter 1 (e.g. 3)
[13] Effect 1: Preset 0: Parameter 1 (e.g. 5)

**Comment by bkshepherd** [comment]
Awesome! I added you as a collaborator.  I look forward to checking it all out!

**Comment by jaching** [comment]
I posted an initial version but missing a few features that I wanted to ask your opinion on.  Unfortunately it adds quite a bit of bloat to the code, which means less effects if running from Flash.

* Reset Presets button within the Presets page
* For MIDI CC Handling: Would you be okay with a user configurable override such that guitar_pedal.cpp invokes the MIDI Received method rather than simply setting the parameter?  Likewise pair this with a "number of consecutive MIDI CC values" integer.  This way the end user can choose to do their own handling of MIDI (e.g. mapping 2 MIDI Bytes to the upper 14 bits of a float).

Also, I'm still working some issues out with the Multi Tapped Delay (for some reason I have inconsistent behavior if I allocate PitchShifter objects to SDRAM, it will work for some builds but not all), but I at least have a rough sample with 2/4 Taps being pitch shifted.
https://www.youtube.com/watch?v=u0BaoX-MdT8

**Comment by bkshepherd** [comment]
The multi-tap delay sounds great!  Nice work!

1) For the reset, I think there is a menu option that just simply calls a function when selected.  That would be the one to use if you add it to the settings menu configurations.   That was something I had been meaning to do!

2) For the MidiCC handling, yeah that sounds great.  Let the effect module itself have a function to accept midi CC and let it decide how to handle it.  I'd still make sure to provide default handling for the typical use case though in the base class.

**Comment by jaching** [comment]
Thanks, its been a lot of fun to work on!  I am astonished that I can process 4 separate pitchshifter objects simultaneously without crackling, but then again my only frame of reference is trying something similar thing with a much more CPU Intensive pitch shifting in MaxMsp a year or so ago. 

1. Ah, I completely missed that somehow.  This has been added.
2. After some more thought, I decided the easiest way without adding too much more overhead is to just use a virtual function from the base effect class to allow the user to decide what to do with the Midi CC.  Currently to not add to much more logic/overhead, the guitar_pedal class will call this function from the Active Effect when it cannot find the parameter.

I'm starting a PR with the initial version of the Multi Delay class that is useable, along with everything else in this topic, to not hold up this issue any further.  Please have a look and let me know if there are any issues!

**Comment by bkshepherd** [comment]
Thanks for getting this submitted a pull request!  I'm going to try to take a look this weekend and get it merged in.

**Comment by bkshepherd** [comment]
Merged in the Storage Presets Display Update. This issue is closed!
