### ISSUE TITLE
MIDI cc controls not working

### ISSUE THREAD

**Issue by GuitarML** [bkshepherd/DaisySeedProjects#42]
When using the latest code, sending midi cc messages to control effect parameters doesn't seem to work correctly. On an older build it does work (I think before the custom display values were added, around Feb 2024). It seems to detect the message, because the screen flickers but immediately goes to "0.0". Is there a way to use midi controls with the updated value and preset handling? Thanks!

**Comment by xconverge** [comment]
Which effect? All of them?

I wonder if the screen logic is taking priority

I don't have any midi stuff to really test unfortunately, I could try to rig something up in the near future though

**Comment by GuitarML** [comment]
I changed most of the effect midi mapping to match my midi controller, so there's something going on besides it being set to -1. I haven't tried switching the effects over midi, I'm guessing that's a program change midi message rather than CC? Still learning about midi myself but I can take a look at the code to try to understand the logic for it.

**Comment by bkshepherd** [comment]
I have a feeling this got broken when the underlying values used to store parameters changed from 8bit uints to 32bit bytes that could represent more data types.  The midi cc commands were taking advantage of the fact that the underlying data structure was the same range as the allowable midi values.  I bet it just needs to cal the appropriate setter functions for the data type instead of assuming the underlying is a uint and setting the RAW bytes.

**Comment by GuitarML** [comment]
@bkshepherd it also looks like the logic for each data type is different than the old code when updating the UI. Before, unknown/raw/float values were all grouped into one "if" statement, but now the float data type is separated out and only sets as float, instead of setting as raw. So the parameters I'm changing that are set as "FloatMagnitude" type, it never gets to the logic to update the raw value, it only tries to update the float value. But since it's midi it's only receiving an int value. I'll try setting a parameter as a "Raw" data type and see if midi works for it then.

**Comment by GuitarML** [comment]
@bkshepherd is it possible to convert the uint8 received by midi into a uint32 before sending to the set raw function? Or was there a particular setter function in the code you are referring to that I should use.

**Comment by bkshepherd** [comment]
@GuitarML Yeah, I think this is the root of the problem.  You can't just convert the midi uint8 to uint32 and set the parameter and hope it works because there are many parameter types now.  In the handle midi function you'd probably need to special case the default behavior for the actual parameter type.  For instance.  if the param is a bool.  use the midi 0..127 for False and 128..255 as True. For Parameters that are 0..1 magnitude map the midi 0..255 to 0.0 to 1.0 range with discrete increments.  For the binned value convert the midi 0..255 to minValue->maxValue.   I think I had also thought about adding a callback to specific effect_Modules to allow them to override default midi conversion mappings to get this logic out of the main guitar_pedal.cpp, but I clearly never got around to doing this.

**Comment by xconverge** [comment]
> @GuitarML Yeah, I think this is the root of the problem. You can't just convert the midi uint8 to uint32 and set the parameter and hope it works because there are many parameter types now. In the handle midi function you'd probably need to special case the default behavior for the actual parameter type. For instance. if the param is a bool. use the midi 0..127 for False and 128..255 as True. For Parameters that are 0..1 magnitude map the midi 0..255 to 0.0 to 1.0 range with discrete increments. For the binned value convert the midi 0..255 to minValue->maxValue. I think I had also thought about adding a callback to specific effect_Modules to allow them to override default midi conversion mappings to get this logic out of the main guitar_pedal.cpp, but I clearly never got around to doing this.

I believe that callback is there in the base effect module, unused by any effect

**Comment by bkshepherd** [comment]
Yes! MidiCCValueNotification.  I guess that should always be called from guitar_pedal.cpp instead of just being the fall back, and then base_effect_module could have a default implementation as I mentioned above.

**Comment by GuitarML** [comment]
I think I get it, thanks! When you say 0 to 255 you mean 0 to 127 right? Isn't 127 the max midi value or am I confused.

**Comment by bkshepherd** [comment]
Yes, you are correct 0..127 is the midi range.

haha I get it, the struggle is real bending over.  Also, for those 1590b pedals without the screen midi is really the only way to switch effects etc.

**Comment by GuitarML** [comment]
I'm also having trouble using the encoder to change binned item types, it's stuck on the first item when I turn the encoder (you can test on the Modulated Tremolo wave types). Noting it here because it seems like it might be a similar problem to the midi issue.

**Comment by bkshepherd** [comment]
This is a separate issue with the Binned item types.  It got broken when someone changed the underlying storage type for parameters to be 32bit from 8bit, some of the conversion functions didn't get updated.  I opened a separate issue to fix this #44 .

**Comment by bkshepherd** [comment]
This should all be fixed now
